<?php

return [
    '' => 'site/index',
    'about-coral-perfumes' => 'site/about',
    'coral-perfumes-private-label' => 'site/private-label',
    'coral-perfumes-showrooms' => 'site/showrooms',
    'coral-perfumes-contact' => 'site/contact',
    'forgot-password' => 'site/forgot',
    'login-signup' => 'site/login-signup',
    'terms-condition' => 'site/terms-condition',
    'privacy-policy' => 'site/privacy-policy',
    'delivery-information' => 'site/return-policy',
    'contact' => 'site/contact',
    'faq' => 'site/faq',
    'view-cart' => 'cart/mycart',
    'checkout' => 'cart/checkout',
    'check-out' => 'checkout/checkout',
    'confirm-order' => 'checkout/confirm',
    'my-account' => 'myaccounts/user/index',
    'my-orders' => 'myaccounts/my-orders/index',
    'my-reviews' => 'myaccounts/user/my-reviews',
    'wish-list' => 'myaccounts/user/wish-list',
    'personal-info' => 'myaccounts/user/personal-info',
    'change-password' => 'myaccounts/user/change-password',
    'adresses' => 'myaccounts/user/user-address',
    'contact-info' => 'myaccounts/user/update-contact-info',
    'coral-perfumes-blog-detail/<id>' => 'site/blog-detail',
    'coral-perfumes-blogs' => 'site/our-blog',
    'create-your-own' => 'create_your_own/create-your-own/index',
    'category/<id>/<featured>' => 'product/index',
    '<id>' => 'product/index',
    'products/<featured>' => 'product/index',
    'product-detail/<product:\w+(-\w+)*>' => 'product/product_detail',
];
